  const pickupLines = [
        "Are you made of copper and tellurium? Because you're Cu-Te.",
        "Are you a carbon sample? Because I want to date you.",
        "Are you made of helium? Because you make me feel like I'm floating.",
        "Are you a star? Because you're illuminating.",
        "Is your name Saturn? Because I feel a great attraction to you.",
        "Are you a black hole? Because I can't escape your pull.",
        "Are you a shooting star? Because you just caught my eye.",
        "Are you a moon? Because I find you mesmerizing.",
        "Are you a comet? Because you're out of this world.",
        "Are you made of dark matter? Because I can't see you, but I know you're there.",
        "Are you an astronaut? Because you've got the right stuff.",
        "Are you the Sun? Because everything revolves around you.",
        "Are you a supernova? Because you're exploding with beauty.",
        "Are you a nebula? Because you're breathtaking.",
        "Are you a rocket? Because you send me to new heights.",
        "Are you a meteorite? Because you've left a big impression on me.",
        "Are you a constellation? Because you light up my life.",
        "Are you a telescope? Because I can't stop looking at you.",
        "Are you a spaceship? Because you're flying through my dreams.",
        "Are you a pulsar? Because you're radiating with energy.",
        "Are you a quasar? Because you're the brightest object in my universe.",
        "Are you a Martian? Because you're out of this world.",
        "Are you a wormhole? Because you've transported me to another dimension.",
        "Are you an exoplanet? Because I'd travel light-years just to be with you.",
        "Are you a lunar eclipse? Because you've blocked out everything else.",
        "Are you a solar eclipse? Because you've completely captivated me.",
        "Are you a supernova remnant? Because you're a beautiful aftermath.",
        "Are you a white dwarf? Because you're small but incredibly dense.",
        "Are you a red giant? Because you're expanding my universe.",
        "Are you a blue giant? Because you're massive and dazzling.",
        "Are you a brown dwarf? Because you're cool and enigmatic.",
        "Are you a black dwarf? Because you're ancient and mysterious.",
        "Are you a white hole? Because you're the opposite of everything else.",
        "Are you a cosmic ray? Because you're penetrating my atmosphere.",
        "Are you a cosmic string? Because you're connecting everything in my universe.",
        "Are you a pulsating variable star? Because you're constantly changing in brightness.",
        "Are you a white hole? Because you're a theoretical possibility.",
        "Are you a star cluster? Because you're a tight-knit community of stars.",
        "Are you a galaxy? Because you're a vast collection of stars.",
        "Are you a star system? Because you're a family of celestial bodies.",
        "Are you a satellite? Because you're orbiting around me.",
        "Are you a rover? Because you're exploring the depths of my heart.",
        "Are you a space probe? Because you're investigating the mysteries of my soul.",
        "Are you a space station? Because you're in orbit around my heart.",
        "Are you a rocket scientist? Because you've mastered the science of love.",
        "Are you a lunar module? Because you're landing softly in my heart.",
        "Are you an extraterrestrial? Because you're unfamiliar but intriguing.",
        "Are you a celestial event? Because you're causing a sensation.",
        "Are you a solar flare? Because you're releasing energy in my heart.",
        "Are you a galactic collision? Because you're creating fireworks in my soul.",
        "Are you a dark nebula? Because you're hiding secrets within.",
        "Are you a cosmic microwave background? Because you're the echo of the Big Bang.",
        "Are you a space-time continuum? Because you're bending reality around me.",
        "Are you a spacetime singularity? Because you're a point of infinite density.",
        "Are you a multiverse? Because you're existing in parallel dimensions.",
        "Are you a quark-gluon plasma? Because you're a state of matter beyond comprehension.",
        "Are you a cosmic ray burst? Because you're emitting bursts of love energy.",
        "Are you a space-time warp? Because you're distorting the fabric of my reality.",
        "Are you a gravity wave? Because you're causing ripples in my heart.",
        "Are you a dark energy? Because you're accelerating the expansion of my affection.",
        "Are you a white noise? Because you're filling my heart with static.",
        "Are you a pulsar wind? Because you're blowing me away.",
        "Are you a star nursery? Because you're giving birth to new feelings in me.",
        "Are you a gamma-ray burst? Because you're emitting intense bursts of love.",
        "Are you a cosmic inflation? Because you're expanding my love universe.",
        "Are you a planetary nebula? Because you're surrounded by a beautiful shell.",
        "Are you a magnetic field? Because you're attracting me with your charm.",
        "Are you a stellar evolution? Because you're evolving into something beautiful.",
        "Are you a galaxy merger? Because you're merging with my heart.",
        "Are you a cosmic dust? Because you're settling in my soul.",
        "Are you a solar wind? Because you're blowing kisses from the Sun.",
        "Are you a space-time anomaly? Because you're bending the rules of attraction.",
        "Are you a dark matter halo? Because you're surrounding me with mystery.",
        "Are you a space debris? Because you're leaving traces of love in my orbit.",
        "Are you a cosmic void? Because you're filling my emptiness with love.",
        "Are you a space-time vortex? Because you're sucking me into your love.",
        "Are you a cosmic dance? Because you're moving in harmony with my heart.",
        "Are you a gravitational lens? Because you're magnifying my love for you.",
        "Are you a space colony? Because you're colonizing my heart.",
        "Are you a space elevator? Because you're lifting me up to new heights of love.",
        "Are you a space suit? Because you're protecting me from the vacuum of loneliness.",
        "Are you a space tourism? Because you're taking me on a journey to your heart.",
        "Are you a space junk? Because you're cluttering my mind with thoughts of you.",
        "Are you a space debris? Because you're crashing into my heart.",
        "Are you a Wi-Fi signal? Because I'm really feeling a connection.",
        "Are you a campfire? Because you're hot and I want s'more.",
        "Are you a candle? Because you light up my life.",
        "Are you an elevator? Because you're definitely lifting me up.",
        "Are you a magician? Because whenever I look at you, everyone else disappears.",
        "Are you a drum set? Because I want to bang you all night long.",
        "Are you a crossword puzzle? Because I can't figure you out but I want to spend all day trying.",
        "Are you a parking ticket? Because you've got 'FINE' written all over you.",
        "Are you a dictionary? Because you're adding meaning to my life.",
        "Are you a keyboard? Because you're just my type.",
        "Are you a microwave? Because you melt my heart.",
        "Are you a fruit? Because honeydew you know how fine you look right now?",
        "Are you a camera? Because every time I look at you, I smile.",
        "Are you a bank loan? Because you have my interest.",
        "Are you an alarm clock? Because you're always waking me up to reality.",
        "Are you a firework? Because you light up my world.",
        "Are you a diamond? Because you're priceless.",
        "Are you a museum? Because you truly are a work of art.",
        "Are you a staircase? Because you're taking my breath away.",
        "Are you a cake? Because you're so sweet.",
        "Are you a roller coaster? Because with you, every day is an adventure.",
        "Are you a charger? Because without you, I'd quickly run out of energy.",
        "Are you a bank? Because you've stolen my heart.",
        "Are you a magnet? Because you're attracting me from across the room.",
        "Are you a puzzle piece? Because you complete me.",
        "Are you a garden? Because I'm digging you.",
        "Are you a starfish? Because I want to wrap my arms around you and never let go.",
        "Are you a pilot? Because you've flown straight into my heart.",
        "Are you a chair? Because you're supporting me through everything.",
        "Are you a rainbow? Because you add color to my life.",
        "Are you a sweater? Because you're keeping me warm.",
        "Are you a blanket? Because you're comforting.",
        "Are you a cloud? Because you make my day brighter.",
        "Are you a mountain? Because you're breathtaking.",
        "Are you a coin? Because you're a treasure.",
        "Are you a mailbox? Because you're full of surprises.",
        "Are you a map? Because I keep getting lost in your eyes.",
        "Are you a street? Because you're where all my dreams lead.",
        "Are you a puzzle? Because I'm trying to piece you together.",
        "Are you a teddy bear? Because I want to cuddle with you forever.",
        "Are you a pot of gold? Because you're the treasure at the end of my rainbow.",
        "Are you a compass? Because you always point me in the right direction.",
        "Are you a watch? Because every second with you is precious.",
        "Are you a glue stick? Because you hold everything together.",
        "Are you a train? Because you're always on the right track.",
        "Are you a calendar? Because you make my days better.",
        "Are you a tree? Because you're rooted in my heart.",
        "Are you a sunrise? Because you bring light to my darkest days.",
        "Are you a sunset? Because you make every evening beautiful.",
        "Are you a smile? Because whenever I see you, I can't help but smile too.",
        "Are you a snowflake? Because you're one of a kind.",
        "Are you a unicorn? Because you're magical.",
        "Are you a present? Because you're a gift to me.",
        "Are you a cloud? Because you're floating through my mind all day.",
        "Are you a melody? Because you're always stuck in my head.",
        "Are you a flame? Because you're igniting my passion.",
        "Are you a treasure map? Because I'm getting lost in your eyes.",
        "Are you a cookie? Because you're irresistibly sweet.",
        "Are you a feather? Because you're lightening up my day.",
        "Are you a movie? Because you're always playing in my thoughts.",
        "Are you a poet? Because you're speaking to my soul.",
        "Are you a pond? Because you're so deep.",
        "Are you a bubble? Because you make me feel light and happy.",
        "Are you a rocket? Because you're blasting through my heart.",
        "Are you a gem? Because you're precious to me.",
        "Are you a bandage? Because you're healing my wounds.",
        "Are you a drum? Because my heart beats for you.",
        "Are you a clock? Because you're always ticking in my mind.",
        "Are you a book? Because I can't put you down.",
        "Are you a candle? Because you're setting my heart on fire.",
        "Are you a dream? Because you're too good to be true.",
        "Are you a fortress? Because you're protecting my heart.",
        "Are you a comet? Because you're streaking through my universe.",
        "Are you a potion? Because you're intoxicating.",
        "Are you a typewriter? Because you're typing out love letters in my mind.",
        "Are you a pearl? Because you're rare and beautiful.",
        "Are you a ship? Because you're sailing into my heart.",
        "Are you a forest? Because you're full of mysteries.",
        "Are you a plane? Because you're flying high in my thoughts.",
        "Are you a cupcake? Because you're sweet and irresistible.",
        "Are you a dreamcatcher? Because you're catching all my dreams.",
        "Are you a cloud? Because you're raining love on me.",
        "Are you a diamond? Because you're shining bright in my life.",
        "Are you a garden? Because you're blooming beautifully.",
        "Are you a hug? Because I want to wrap my arms around you forever.",
        "Are you a balloon? Because you're lifting my spirits.",
        "Are you a telescope? Because you're showing me a whole new world.",
        "Are you a mirror? Because you're reflecting all the beauty in the world.",
        "Are you a coin? Because you're priceless to me.",
        "Are you a rainbow? Because you're bringing color into my life.",
        "Are you a breeze? Because you're refreshing my soul.",
        "Are you a magnet? Because you're attracting me to you.",
        "Are you a key? Because you're unlocking my heart.",
        "Are you a photograph? Because you're capturing my heart in every shot.",
        "Are you a wave? Because you're washing over me.",
        "Are you a pen? Because you're writing love letters on my heart.",
        "Are you a grape? Because you're crushing on me.",
        "Are you a clock? Because you're keeping perfect time in my heart.",
        "Are you a beacon? Because you're guiding me home.",
        "Are you a melody? Because you're music to my ears.",
        "Are you a puzzle? Because you're making me think of you.",
        "Are you a whisper? Because you're filling my thoughts.",
        "Are you a masterpiece? Because you're a work of art.",
        "Are you a wave? Because you're crashing into me.",
        "Are you a treasure chest? Because you're full of surprises.",
        "Are you a match? Because you're lighting up my life.",
        "Are you a forest? Because you're wild and untamed.",
        "Are you a compass? Because you're guiding me in the right direction.",
        "Are you a dream? Because you're making all my dreams come true.",
        "Are you a comet? Because you're blazing a trail in my heart.",
        "Are you a seed? Because you're planting love in my heart.",
        "Are you a bridge? Because you're connecting me to new heights of love.",
        "Are you a wave? Because you're making waves in my heart.",
        "Are you a rainbow? Because you're brightening up my day.",
        "Are you a mirror? Because you're reflecting all the beauty in the world.",
        "Are you a magnet? Because you're attracting me to you.",
        "Are you a key? Because you're unlocking my heart.",
        "Are you a photograph? Because you're capturing my heart in every shot.",
        "Are you a wave? Because you're washing over me.",
        "Are you a pen? Because you're writing love letters on my heart.",
        "Are you a grape? Because you're crushing on me.",
        "Are you a clock? Because you're keeping perfect time in my heart.",
        "Are you a beacon? Because you're guiding me home.",
        "Are you a melody? Because you're music to my ears.",
        "Are you a puzzle? Because you're making me think of you.",
        "Are you a whisper? Because you're filling my thoughts.",
        "Are you a masterpiece? Because you're a work of art.",
        "Are you a wave? Because you're crashing into me.",
        "Are you a treasure chest? Because you're full of surprises.",
        "Are you a match? Because you're lighting up my life.",
        "Are you a forest? Because you're wild and untamed.",
        "Are you a compass? Because you're guiding me in the right direction.",
        "Are you a dream? Because you're making all my dreams come true.",
        "Are you a comet? Because you're blazing a trail in my heart.",
        "Are you a seed? Because you're planting love in my heart.",
        "Are you a bridge? Because you're connecting me to new heights of love.",
        "Are you a wave? Because you're making waves in my heart.",
        "Are you a rainbow? Because you're brightening up my day."
    ];

const pickupLineDisplay = document.getElementById('pickup-line');
const generateBtn = document.getElementById('generate-btn');

function generateRandomPickupLine() {
    const randomIndex = Math.floor(Math.random() * pickupLines.length);
    pickupLineDisplay.textContent = pickupLines[randomIndex];
    pickupLineDisplay.classList.add('show');
}

generateBtn.addEventListener('click', generateRandomPickupLine);

pickupLineDisplay.addEventListener('transitionend', () => {
    pickupLineDisplay.classList.remove('show');
});

// Generate a random pickup line on page load
generateRandomPickupLine();
